add_executable(spsc_queue_test spsc_queue_test.cpp)
target_link_libraries(spsc_queue_test PRIVATE spsc_queue GTest::gtest_main)
add_test(NAME spsc_queue_test COMMAND spsc_queue_test)

add_executable(spsc_queue_stress_test spsc_queue_stress_test.cpp)
target_link_libraries(spsc_queue_stress_test PRIVATE spsc_queue GTest::gtest_main)
add_test(NAME spsc_queue_stress_test COMMAND spsc_queue_stress_test)
